USE HR;
-- cau a
SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY > 12000

SELECT *
FROM EMPLOYEES
WHERE SALARY > 12000

-- cau b
SELECT FIRST_NAME,LAST_NAME,DEPARTMENT_ID
FROM EMPLOYEES
WHERE EMPLOYEE_ID = 176

--cau c
SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY not between 5000 and 12000

--- cau d
SELECT FIRST_NAME,LAST_NAME,JOB_ID,HIRE_DATE
FROM EMPLOYEES
WHERE  HIRE_DATE between '1998/02/20' and '1998/05/01'

_--cach 2 : chuyen doi kieu
SELECT FIRST_NAME,LAST_NAME,JOB_ID,HIRE_DATE
FROM EMPLOYEES
WHERE  HIRE_DATE between CONVERT(date,'20/02/1998',103) and
                         CONVERT(date,'01/05/1998',103)

--cau e
SELECT FIRST_NAME, LAST_NAME ,DEPARTMENT_ID
FROM  EMPLOYEES
WHERE DEPARTMENT_ID in (20,50) 
---Toán tử in: tập hợp là để lấy dữ liệu ở số 20 và 60

-- cau f
SELECT LAST_NAME as Employee, SALARY as [Mothly salary]
FROM EMPLOYEES
WHERE SALARY between 5000 and 12000 
and DEPARTMENT_ID in (20,50)
---Có khoảng trắng thì khai bằng [] hoặc ''
--cau g, 
select LAST_NAME,JOB_ID,HIRE_DATE
from EMPLOYEES
where YEAR(HIRE_DATE) = 1994

--Cau h
SELECT LAST_NAME,JOB_ID
FROM EMPLOYEES
WHERE MANAGER_ID IS NULL 

--BI QUAN LY
SELECT LAST_NAME,JOB_ID
FROM EMPLOYEES
WHERE MANAGER_ID IS NOT NULL

-- CAU I
SELECT LAST_NAME,SALARY, COMMISSION_PCT
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL
ORDER BY  SALARY DESC, COMMISSION_PCT DESC 
--DESC là giảm dân, asc là tăng dần (k cần nhập vào), khai báo biến not null vì có biến null là k phải nv kinh doanh cần loại trừ

--cách khác
SELECT LAST_NAME,SALARY, COMMISSION_PCT
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL
ORDER BY 2  DESC, 3 DESC

---cau j
SELECT LAST_NAME
FROM EMPLOYEES
WHERE  LAST_NAME like '__a%'

---cau k
SELECT LAST_NAME
FROM EMPLOYEES
WHERE LAST_NAME like '%a%' or LAST_NAME like '%e%' or LAST_NAME like '__a%'

--cau l 
SELECT LAST_NAME,JOB_ID,SALARY
FROM EMPLOYEES
WHERE JOB_ID in ('SA_REP','ST_CLERK')
--để trong '' do job_id là kí tự k phải là số
--số k cần để trong '', kí tự phải để trong ''

